FROM alpine:edge
# tinyproxy 1.8.4
# nghttp2 1.23
RUN  apk add --no-cache --update tinyproxy nghttp2 \
 &&  mkdir -m 777 /config 
ENV SERVER_CRT="-----BEGIN CERTIFICATE-----MIIC/jCCAoSgAwIBAgIBATAKBggqhkjOPQQDAjCBrzELMAkGA1UEBhMCQ04xEjAQBgNVBAgTCUd1YW5nRG9uZzESMBAGA1UEBxMJR3VhbmdaaG91MQ0wCwYDVQQKEwRobGtqMRAwDgYDVQQLDAdobGtqX3N0MTMwMQYDVQQDDCoqLjFkMzUuc3RhcnRlci11cy1lYXN0LTEub3BlbnNoaWZ0YXBwcy5jb20xIjAgBgkqhkiG9w0BCQEWE2h1b2xvbmdrZWppQGFvbC5jb20wHhcNMTgwMjA2MTMxMzAwWhcNMjgwMjA2MTMxMzAwWjCBrzELMAkGA1UEBhMCQ04xEjAQBgNVBAgTCUd1YW5nRG9uZzESMBAGA1UEBxMJR3VhbmdaaG91MQ0wCwYDVQQKEwRobGtqMRAwDgYDVQQLDAdobGtqX3N0MTMwMQYDVQQDDCoqLjFkMzUuc3RhcnRlci11cy1lYXN0LTEub3BlbnNoaWZ0YXBwcy5jb20xIjAgBgkqhkiG9w0BCQEWE2h1b2xvbmdrZWppQGFvbC5jb20wdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQ6cntux5ylVmjCN1qd30QKY5YGIO6JitLGWuID3hRJOzeDD8v5d6wRpeYa6SOBJeTc5uWF76Ym1xh9BYIGPL3UCQ79hCf+UaNf5arHlISbKFjbPffXz+URBdxBC0ovZYGjcjBwMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHwEveH5uVULARjHNEijhibIAB1FMAsGA1UdDwQEAwIBBjARBglghkgBhvhCAQEEBAMCAAcwHgYJYIZIAYb4QgENBBEWD3hjYSBjZXJ0aWZpY2F0ZTAKBggqhkjOPQQDAgNoADBlAjEAj9r98mzAQ7m4Yfj3hbPWi6bxUnK6JDOgxx1FTxc9mVuqKayqELK1mzdAhusN8Eg3AjAkAyar4231gz+4RXk2xiT0RCHIsmHYROxQmMjnGHY9iiYWbYiBTy7qeLvlz7zeI3s=-----END CERTIFICATE-----" SERVER_KEY="-----BEGIN EC PRIVATE KEY-----MIGkAgEBBDARtdEZGXybC2xca1hS3/eYfGeH1J6E/XvwCz5K+5YauW+NxpKcbJ8IsK31F56+qG+gBwYFK4EEACKhZANiAAQ6cntux5ylVmjCN1qd30QKY5YGIO6JitLGWuID3hRJOzeDD8v5d6wRpeYa6SOBJeTc5uWF76Ym1xh9BYIGPL3UCQ79hCf+UaNf5arHlISbKFjbPffXz+URBdxBC0ovZYE=-----END EC PRIVATE KEY-----"
ADD entrypoint.sh /entrypoint.sh

ADD tinyproxy.conf /config/tinyproxy.conf
ADD nghttpx.conf   /config/nghttpx.conf

RUN  chmod +x /entrypoint.sh \
 &&  chgrp -R 0 /config \
 &&  chmod -R g+rwX /config 
     
ENTRYPOINT  sh /entrypoint.sh

EXPOSE 8443
